#!/bin/bash
ssh-keygen -t rsa -b 2048 -f userA
ssh-keygen -t rsa -b 2048 -f userB
echo "this is some data to encrypt." >data_to_encrypt.txt
openssl dgst -sha256 -sign userA -out signature.txt data_to_encrypt.txt
openssl rsautl -encrypt -pubin -inkey userB.pub -in data_to_encrypt.txt
openssl rsautl -decrypt -pubin -inkey userB -in encrypted_data.bin -out data_to_encrypt.txt
